name: Lint Check

on:
  workflow_call:
    null

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/runner:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configure CMake
        run: /workspace/tools/build.py -cl

      - name: Run clang-tidy
        continue-on-error: true
        run: |
          python3 clang-tidy-diff.py      \
          -p1                             \
          -path .                         \
          < <(git diff -U0 origin/master)