name: Mainline

on:
  pull_request:
    branches:
      - master

jobs:
  permissions:
      packages: write

  prepare:
    uses: ./.github/workflows/prepare.yaml
    secrets: inherit

  lint:
    needs: prepare
    uses: ./.github/workflows/lint.yaml
    secrets: inherit

  test:
    needs: prepare
    uses: ./.github/workflows/test.yaml
    secrets: inherit
