name: Mainline

on:
  pull_request:
    branches:
      - master

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yaml

  lint:
    needs: prepare
    uses: ./.github/workflows/lint.yaml

  test:
    needs: prepare
    uses: ./.github/workflows/test.yaml
